

---






# Missing Data





What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated. For example, for a survey, a `Salary` field with an empty value, or a number 0, or an invalid value (a string for example) can be considered "missing data". These concepts are related to the values that Python will consider "Falsy":

In [2]:
import numpy as np
import pandas as pd


In [ ]:
falsy_values = (0 ,False, None, '', [], {})

For Python, all the values above are considered "falsy":

In [ ]:
any(falsy_values)

False

Numpy has a special "nullable" value for numbers which is `np.nan`. It's *NaN*: "Not a number"

In [ ]:
np.nan

nan

The `np.nan` value is kind of a virus. Everything that it touches becomes np.nan:

In [ ]:
3  + np.nan

nan

In [ ]:
3 * np.nan

nan

As we said, `np.nan` is like a virus. If you have any `nan` value in an array and you try to perform an operation on it, you'll get unexpected results:


In [ ]:
a = np.array([1,2,3,4,np.nan,np.nan,5])
a

array([ 1.,  2.,  3.,  4., nan, nan,  5.])

In [ ]:
a.sum().item()                                      # Adding ".item()" to avoid getting the data type along with the value

nan

In [ ]:
a.mean()

np.float64(nan)

Numpy also supports an "Infinite" type:

In [23]:
np.inf

inf

Which also behaves as a virus:

In [27]:
3 + np.inf

inf

In [28]:
np.inf / 3

inf

In [29]:
np.inf / np.inf

nan


For a numeric array, the `None` value is replaced by `np.nan`:

In [ ]:
a = np.array([1,2,3,4,np.nan,np.nan,None,5], dtype=np.float128)
a

array([ 1.,  2.,  3.,  4., nan, nan, nan,  5.], dtype=float128)

In [34]:
b = np.array([1,2,3,4,np.nan,np.inf,5], dtype=np.float128)
b

array([ 1.,  2.,  3.,  4., nan, inf,  5.], dtype=float128)

In [36]:
b.sum()

np.longdouble('nan')

# Checking for `nan` or `inf`

There are two functions: `np.isnan` and `np.isinf` that will perform the desired checks:

In [39]:
np.isnan(np.nan).item()

True

In [43]:
np.isinf(np.inf).item()

True

And the joint operation can be performed with `np.isfinite`.

In [46]:
np.isfinite(np.nan), np.isfinite(np.inf)

(np.False_, np.False_)

`np.isnan` and `np.isinf` also take arrays as inputs, and return boolean arrays as results:

In [47]:
np.isnan(np.array([1,2,3,np.nan,np.inf,5], dtype=np.float128))

array([False, False, False,  True, False, False])

In [53]:
np.isinf(np.array([1,2,3,4,np.nan,np.inf,5], dtype=np.float128))


array([False, False, False, False, False,  True, False])

In [54]:
np.isfinite(np.array([1,2,3,np.nan,np.inf,5], dtype=np.float128))

array([ True,  True,  True, False, False,  True])

Note: It's not so common to find infinite values. From now on, we'll keep working with only `np.nan`



---


# Filtering them out
Whenever you're trying to perform an operation with a `Numpy` array and you know there might be missing values, you'll need to filter them out before proceeding, to avoid ` nan` propagation. We'll use a combination of the previous `np.isnan` + boolean arrays for this purpose:

In [55]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [56]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

Which is equivalent to:

In [59]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

And with that result, all the operation can be now performed:

In [63]:
a[np.isfinite(a)].sum().item()

10.0

In [66]:
a[np.isfinite(a)].mean().item()

2.5



---

